name: venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aniso8601=8.0.0
  - appdirs=1.4.3
  - beautifulsoup4=4.9.1
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - cudatoolkit=10.0.130
  - flask=1.1.2
  - flask-restful=0.3.8
  - freetype=2.10.2
  - googledrivedownloader=0.4
  - idna=2.10
  - importlib-metadata=1.7.0
  - intel-openmp=2020.1
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - markdown=3.2.2
  - markupsafe=1.1.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ninja=1.9.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.0.5
  - pillow=7.2.0
  - pip=20.1.1
  - prettytable=0.7.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python-wget=3.2
  - python_abi=3.7
  - pytz=2020.1
  - requests=2.24.0
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - setuptools=47.3.1
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.32.3
  - threadpoolctl=2.1.0
  - tika=1.24
  - tk=8.6.10
  - torchvision=0.4.0
  - tqdm=4.47.0
  - urllib3=1.25.9
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - filelock==3.0.12
    - packaging==20.4
    - pyparsing==2.4.7
    - regex==2020.6.8
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - tokenizers==0.7.0
    - transformers==2.11.0
    - beautifulsoup4==4.9.1
    - Flask-RESTful==0.3.8